apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
      - name: polybot-container
        image: joumanakh/polybotimage1-aws:11
        env:
        - name: TELEGRAM_APP_URL
          value: "https://joumanakh.atech-bot.click:443"
        - name: BUCKET_NAME
          value: "joumanakhbucket"
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: polybot-service
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8443
  type: ClusterIP
